# **BÁO CÁO BỘ DỮ LIỆU**

Bộ dữ liệu được thu thập từ trang web https://books.toscrape.com/

Đây là một trang web giả lập dạng cửa hàng bán sách trực tuyến, được thiết kế đặc biệt dành riêng cho mục đích học tập và thực hành.

Trang web chứa thông tin giả định của khoảng 1.000 cuốn sách chia thành nhiều thể loại/danh mục khác nhau. Mỗi đầu sách cung cấp đầy đủ các trường thông tin cơ bản như: tiêu đề, giá tiền, trạng thái còn hàng, rating và link ảnh bìa.

Ở Catalogue của trang, có 50 trang, mỗi trang gồm 20 cuốn sách.

Trong bài tập lần này, tôi quyết định thu thập tất cả 50 trang vào file data.csv và thống kê cơ bản về bộ dữ liệu thu thập được.

In [1]:
from google.colab import files
import pandas as pd

files.upload()

df = pd.read_csv("data.csv")

print("Số dòng:", df.shape[0])
print("Số cột:", df.shape[1])

Saving data.csv to data.csv
Số dòng: 1000
Số cột: 5

In [2]:
df.head()

,title,price,rating,availability,link
0,A Light in the Attic,51.77,3,In stock,https://books.toscrape.com/catalogue/a-light-i...
1,Tipping the Velvet,53.74,1,In stock,https://books.toscrape.com/catalogue/tipping-t...
2,Soumission,50.10,1,In stock,https://books.toscrape.com/catalogue/soumissio...
3,Sharp Objects,47.82,4,In stock,https://books.toscrape.com/catalogue/sharp-obj...
4,Sapiens: A Brief History of Humankind,54.23,5,In stock,https://books.toscrape.com/catalogue/sapiens-a...

In [3]:
df.tail()

,title,price,rating,availability,link
995,Alice in Wonderland (Alice's Adventures in Won...,55.53,1,In stock,https://books.toscrape.com/catalogue/alice-in-...
996,"Ajin: Demi-Human, Volume 1 (Ajin: Demi-Human #1)",57.06,4,In stock,https://books.toscrape.com/catalogue/ajin-demi...
997,A Spy's Devotion (The Regency Spies of London #1),16.97,5,In stock,https://books.toscrape.com/catalogue/a-spys-de...
998,1st to Die (Women's Murder Club #1),53.98,1,In stock,https://books.toscrape.com/catalogue/1st-to-di...
999,"1,000 Places to See Before You Die",26.08,5,In stock,https://books.toscrape.com/catalogue/1000-plac...

# **Giải thích tên các thuộc tính**
title: tên sách

price: giá sách

rating: số sao

availability: tình trạng sách ("in stock": còn hàng ; "out of stock": hết hàng)

link: đường dẫn đến trang của sách

In [4]:
print(df.columns.tolist())

['title', 'price', 'rating', 'availability', 'link']

In [5]:
print("Các kiểu dữ liệu:")
df.dtypes

Các kiểu dữ liệu:

title            object
price           float64
rating            int64
availability     object
link             object
dtype: object

In [6]:
print("Thông tin dataset:")
df.info()

Thông tin dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         1000 non-null   object
 1   price         1000 non-null   float64
 2   rating        1000 non-null   int64
 3   availability  1000 non-null   object
 4   link          1000 non-null   object
dtypes: float64(1), int64(1), object(3)
memory usage: 39.2+ KB

In [7]:
print("Thống kê các biến số:")
df.describe()

Thống kê các biến số:

            price       rating
count  1000.00000  1000.000000
mean     35.07035     2.923000
std      14.44669     1.434967
min      10.00000     1.000000
25%      22.10750     2.000000
50%      35.98000     3.000000
75%      47.45750     4.000000
max      59.99000     5.000000

In [8]:
print("Số lượng giá trị thiếu:")
df.isna().sum()

Số lượng giá trị thiếu:

title           0
price           0
rating          0
availability    0
link            0
dtype: int64

In [10]:
print("Số lượng dòng trùng:")
df.duplicated().sum()

Số lượng dòng trùng:

np.int64(0)

# **Kết luận**
Sau các bước thống kê dữ liệu cơ bản, có thể kết luận như sau:
- Bộ dữ liệu thu thập được có 5 cột và 1000 dòng.
- Bộ dữ liệu vô cùng sạch, không có giá trị NaN, không có dòng trùng, không có giá trị thiếu.